name: absensi
version: 2.3.45+36
publish_to: none
description: URBAN&CO SPOT
environment: 
  sdk: 3.7.2

dependencies: 
  awesome_dialog: ^3.2.1
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  datetime_picker_formfield: 2.0.1
  device_info_null_safety: 0.0.3
  device_marketing_names: ^0.9.1
  file_picker: ^8.0.5
  # flutter_barcode_scanner: 2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_map: 6.1.0
  flutter_map_location_marker: any
  flutter_native_timezone_updated_gradle: 2.0.3
  flutter_smart_dialog: ^4.9.8+1
  flutter_typeahead: 4.8.0
  fluttertoast: ^8.2.2
  geocoding: 3.0.0
  geolocator: ^11.1.0
  get: ^4.6.6
  http: ^1.1.0
  http_parser: 4.0.2
  icons_plus: 5.0.0
  image_picker: 1.1.2
  intl: ^0.19.0
  latlong2: ^0.9.0
  lottie: ^3.1.2
  ota_update: 6.0.0
  package_info_plus: ^8.0.2
  pdf: ^3.11.1
  percent_indicator: ^4.2.3
  permission_handler: ^11.0.1
  photo_view: ^0.15.0
  printing: 5.12.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  splash_screen_view: any
  sqflite: ^2.3.3+1
  xml: ^6.2.2
  expansion_tile_group: 2.0.0
  widget_zoom: ^0.0.4
  path: ^1.9.0
  # flutter_speed_dial: 7.0.0
  url_launcher: ^6.3.1
  day_night_time_picker: ^1.3.1
  marquee: 2.3.0
  fading_edge_scrollview: ^4.1.1
  flutter: 
    sdk: flutter
  flutter_dotenv: ^5.2.1
  table_calendar: ^3.1.3
  awesome_bottom_bar: ^1.2.4
  slider_button: ^2.1.0
  qr_code_scanner: 1.0.1
  signature: ^6.3.0
  uuid: ^4.5.1
  step_progress: ^2.6.0
  # google_mobile_ads: ^6.0.0
  startapp_sdk: ^1.0.1
  custom_refresh_indicator: ^4.0.1
  month_year_picker: ^0.4.0+1
  # firebase_core: ^3.4.0
  # firebase_messaging: ^15.1.0
  # flutter_local_notifications: ^16.1.0

dev_dependencies: 
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter

flutter_launcher_icons: 
  android: launcher_icon
  image_path: assets/image/selfie.png
  web: 
    image_path: assets/image/selfie.png
    background_color: '#hexcode'
    theme_color: '#hexcode'
    generate: true
  windows: 
    image_path: assets/image/selfie.png
    generate: true
    icon_size: 48
  macos: 
    image_path: assets/image/selfie.png
    generate: true
  ios: true
  min_sdk_android: 21

flutter: 
  assets: 
    - assets/image/
    - assets/sound/
    - assets/animation/
    - assets/.env
  fonts: 
    - family: Nunito
      fonts: 
        - asset: assets/fonts/Nunito-Black.ttf
        - asset: assets/fonts/Nunito-BlackItalic.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito-BoldItalic.ttf
        - asset: assets/fonts/Nunito-Italic.ttf
        - asset: assets/fonts/Nunito-Light.ttf
        - asset: assets/fonts/Nunito-LightItalic.ttf
        - asset: assets/fonts/Nunito-Medium.ttf
        - asset: assets/fonts/Nunito-Regular.ttf
  uses-material-design: true
  # plugin:
  #   platforms:
  #     android:
  #       package: com.amolg.flutterbarcodescanner
  #       pluginClass: FlutterBarcodeScannerPlugin
  #     ios:
  #       pluginClass: SwiftFlutterBarcodeScannerPlugin

